esphome:
  name: test-build
  friendly_name: Test Build

esp8266:
  board: d1_mini

# WiFi configuration (required for compilation)
wifi:
  ssid: "test"
  password: "test12345678"
  min_auth_mode: WPA2

# Enable API
api:

# Enable logging (but not via UART)
logger:
  baud_rate: 0

external_components:
  - source: 
      type: local
      path: esphome/components
    components: [midea_xye]
  
# UART settings for RS485 converter dongle (required)
uart:
  tx_pin: TX
  rx_pin: RX
  baud_rate: 4800

# Main settings
climate:
  - platform: midea_xye
    name: Test Heatpump
    period: 1s
    timeout: 100ms
    use_fahrenheit: false
